# Generated by Django 6.0.6 on 2026-06-21 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_remove_empleado_fecha_creacion_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('total_planilla', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_quincenal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_extra_diurnas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('isss_empleado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('afp_empleado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('isss_patronal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('afp_patronal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('liquido_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='planillas.planilla')),
            ],
            options={
                'ordering': ['empleado__nombre_completo'],
            },
        ),
    ]
