# Generated by Django 6.0.6 on 2026-06-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='aguinaldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='costo_patronal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='quincena_25',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='renta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='total_descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='total_devengado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='vacaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
