# Generated by Django 6.0.6 on 2026-06-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0002_remove_planilla_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_isss_empleado', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('porcentaje_isss_patronal', models.DecimalField(decimal_places=2, default=7.5, max_digits=5)),
                ('porcentaje_afp_empleado', models.DecimalField(decimal_places=2, default=7.25, max_digits=5)),
                ('porcentaje_afp_patronal', models.DecimalField(decimal_places=2, default=8.75, max_digits=5)),
                ('tope_isss', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración Planilla',
                'verbose_name_plural': 'Configuración Planilla',
            },
        ),
    ]
