# Generated by Django 6.0.6 on 2026-06-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0003_configuracionplanilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramoAguinaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiguedad_desde', models.IntegerField()),
                ('antiguedad_hasta', models.IntegerField(blank=True, null=True)),
                ('dias_aguinaldo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orden', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Tramo Aguinaldo',
                'verbose_name_plural': 'Tramos Aguinaldo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TramoISR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('QUINCENAL', 'QUINCENAL'), ('MENSUAL', 'MENSUAL')], default='QUINCENAL', max_length=20)),
                ('desde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hasta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exceso_sobre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota_fija', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Tramo ISR',
                'verbose_name_plural': 'Tramos ISR',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='configuracionplanilla',
            name='antiguedad_minima_quincena_25',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configuracionplanilla',
            name='aplicar_exencion_aguinaldo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionplanilla',
            name='limite_exento_aguinaldo',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracionplanilla',
            name='porcentaje_quincena_25',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='aguinaldo_exento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='aguinaldo_gravado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='aplico_aguinaldo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='aplico_quincena_25',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='aplico_vacaciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='base_gravada_isr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
