# Generated by Django 6.0.6 on 2026-06-21 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EMPLEADOS', 'Empleados'), ('PLANILLAS', 'Planillas'), ('PDF', 'PDF'), ('PRODUCTOS', 'Productos'), ('COMPRAS', 'Compras'), ('VENTAS', 'Ventas'), ('ASISTENCIAS', 'Asistencias'), ('AUSENCIAS', 'Ausencias'), ('CONFIGURACION', 'Configuración'), ('SISTEMA', 'Sistema')], max_length=30)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('GENERAR', 'Generar'), ('DESCARGAR', 'Descargar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTRAR', 'Registrar')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
