# Generated by Django 6.0.6 on 2026-06-21 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_remove_empleado_fecha_creacion_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AusenciaIncapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUSENCIA', 'Ausencia'), ('INCAPACIDAD', 'Incapacidad'), ('PERMISO', 'Permiso'), ('LLEGADA_TARDE', 'Llegada tarde')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='incapacidades/')),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('JUSTIFICADO', 'Justificado'), ('NO_JUSTIFICADO', 'No justificado')], default='REGISTRADO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias_incapacidades', to='empleados.empleado')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
