# Generated by Django 6.0.6 on 2026-06-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dui', models.CharField(max_length=10, unique=True)),
                ('numero_isss', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_ingreso', models.DateField()),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
