# Generated by Django 6.0.6 on 2026-06-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
