# Generated by Django 6.0.6 on 2026-06-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleado_fecha_creacion_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre_completo']},
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='jornada',
            field=models.CharField(choices=[('TIEMPO_COMPLETO', 'Tiempo completo'), ('MEDIO_TIEMPO', 'Medio tiempo'), ('POR_HORAS', 'Por horas')], default='TIEMPO_COMPLETO', max_length=30),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('TEMPORAL', 'Temporal'), ('SERVICIOS', 'Servicios profesionales'), ('MEDIO_TIEMPO', 'Medio tiempo')], default='INDEFINIDO', max_length=30),
        ),
    ]
