# Generated by Django 6.0.6 on 2026-06-21 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_alter_empleado_options_empleado_fecha_fin_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('PERMISO', 'Permiso'), ('INCAPACIDAD', 'Incapacidad'), ('VACACION', 'Vacación')], default='PRESENTE', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='empleados.empleado')),
            ],
            options={
                'ordering': ['-fecha', 'empleado__nombre_completo'],
            },
        ),
    ]
